version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VESION}
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elknet

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VESION}
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /etc/logstash/conf.d/
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
      - type: bind
        source: ./logstash/drivers/postgresql-42.2.10.jar
        target: /usr/share/logstash/logstash-core/lib/jars/postgresql-42.2.10.jar
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      PGSQL_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/b3"
      PGSQL_JDBC_DRIVER: "org.postgresql.Driver"
      PGSQL_JDBC_DRIVER_JAR_LOCATION: "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.2.10.jar"
      PGSQL_JDBC_USERNAME: logstash_user
      PGSQL_JDBC_PASSWORD: logstash
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    networks:
      - elknet   
    depends_on:
      - elasticsearch
      
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VESION}
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elknet
    depends_on:
      - elasticsearch

networks:
  elknet:
    driver: bridge

volumes:
  elasticsearch: