- pipeline.id: logstash
  path.config: /usr/share/logstash/pipeline/logstash.conf
  pipeline.workers: 1
- pipeline.id: products
  path.config: /usr/share/logstash/pipeline/products.conf
  pipeline.workers: 1